# Generated by Django 3.0 on 2021-01-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201123_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Process title  ')),
            ],
        ),
        migrations.AlterField(
            model_name='input',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource_process', to='classroom.Task', verbose_name='Task Input '),
        ),
    ]
