# Generated by Django 3.0 on 2021-01-03 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210103_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_name',
            field=models.CharField(blank=True, help_text='User, ', max_length=270, null=True, verbose_name='Type or Name   '),
        ),
        migrations.CreateModel(
            name='Technologie_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologie_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Technoly :  ')),
                ('technology_maturity', models.CharField(blank=True, max_length=270, null=True, verbose_name="Technology's maturity :  ")),
                ('autre', models.CharField(blank=True, max_length=270, null=True, verbose_name='if other partner ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_tech_act', to='classroom.Partner', verbose_name='Select Your University  ')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_act', to='classroom.Activity', verbose_name='Activity ')),
            ],
        ),
        migrations.CreateModel(
            name='Skill_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Skill title:  ')),
                ('skills_maturity', models.CharField(blank=True, max_length=270, null=True, verbose_name='Skill maturity :  ')),
                ('autre', models.CharField(blank=True, max_length=270, null=True, verbose_name='if other partner ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_skill_act', to='classroom.Partner', verbose_name='Select Your University  ')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_act', to='classroom.Activity', verbose_name='Activity  ')),
            ],
        ),
        migrations.CreateModel(
            name='Output_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Output title ')),
                ('autre', models.CharField(blank=True, max_length=270, null=True, verbose_name='if other partner ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_out_act', to='classroom.Partner', verbose_name='Select Your University  ')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_act', to='classroom.Activity', verbose_name='Activity Output ')),
            ],
        ),
        migrations.CreateModel(
            name='Input_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Input   ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_input_act', to='classroom.Partner', verbose_name='Select Your University  ')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource_act', to='classroom.Activity', verbose_name='Activity Input ')),
            ],
        ),
        migrations.CreateModel(
            name='Decision_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_name', models.CharField(blank=True, max_length=270, null=True, verbose_name='Decision title   ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_dec_act', to='classroom.Partner', verbose_name='Select Your University  ')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_act', to='classroom.Activity', verbose_name='Activity Decision ')),
            ],
        ),
        migrations.CreateModel(
            name='Actor_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, help_text='User, ', max_length=270, null=True, verbose_name='Type or Name   ')),
                ('autre', models.CharField(blank=True, max_length=270, null=True, verbose_name='if other partner ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_act_act', to='classroom.Partner', verbose_name='Select Your University  ')),
                ('task_id', models.ManyToManyField(blank=True, help_text=' help text.', related_name='actor_act', to='classroom.Activity', verbose_name='Actor_proces  ')),
            ],
        ),
    ]
